apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend
  labels:
    app: node-api
    tier: backend
spec:
  replicas: 10
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: node-api
          image: "elisiomualumene/node_api:latest"
